:sparkles: 회원정보 추가
spartaKotlinTeamSober/wachu_server pull request #103
Opened 2024-08-12 06:50 UTC by ckhcree

## 요약

> 회원정보쪽

## 작업 사항

> 회원가입 이미지 + 회원정보 변경 (메일주소, 비번, 닉네임, 이미지)

## 리뷰 요청 사항(선택)

> 회원정보 수정시 email 변경이 있다면 따로 컨펌해줘야해요
> 근데 그 과정에서 인증코드 발송여부를 클라이언트에게 보여주지 못합니다ㅠㅠ

---

### 해결한 이슈

closes: #99

2024-08-12 07:23 UTC, mobzzzzz requested changes

2024-08-12 07:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        multipartFile?.let {
addMemeber 한 순간 repository에 save 되는 걸로 아는데 member.profileImageUrl 을 먼저 설정하셔야 할 것 같습니다!

2024-08-12 07:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +            member.password = passwordEncoder.encode(it)
Entity를 직접적으로 참조해서 사용하지 말고 Entity 멤버 함수로 `changePassword(password)` 처럼 만들어서 설정하시는게 좋을 것 같네요!

밑에 nickname, profileImageUrl 도 동일합니다

2024-08-12 07:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +            codeService.sendCode(request.email)
Request 안에서 Email 변경까지 이뤄지면 FE에서 한번에 처리하기 좀 애매할 텐데

원래 생각했던 방식은
1. 멤버가 이메일을 바꾸고 싶어함
2. 멤버가 이메일칸에 이메일을 적고 이메일 코드 발송 버튼을 누름
3. 이메일 코드 칸에 코드를 적고 수정 버튼을 눌렀을 때 코드가 일치해야만 수정 완료, 코드가 안맞으면 에러

그래서 codeService.sendCode 하는 부분은 별도로 필요 없어 보이기도 합니다.
request 에 code를 같이 보내는 회원가입과 같은 방식이면 충분할 것 같기도 하네요
그러면 `confirmUpdateEmail` 쪽 로직이 이 updateProfile 로 넘어올 것 같네요

이게 별로같다면 밑에 작성해주신 `confirmUpdateEmail` 을 그대로 사용하는 방법도 있는데
FE에서도 이메일 변경쪽만 별도로 버튼을 추가해서 이메일용 발송 / 수정을 따로 두는 방식입니다.

추가로 다른 시나리오로 멤버가 이메일을 안바꾸면 request에 null 일테니 조건을 통과 못해서 상관 없을 것 같습니다.

2024-08-12 07:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/UpdateRequest.kt
> +data class UpdateRequest(
그냥 `UpdateRequest` 라는 이름은 너무 부정확하니 `ProfileUpdateRequest` 로 하죠!

2024-08-12 07:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    @PatchMapping("/auth/profile/email-update")
`/auth` prefix는 인증 관련에 쓰는 prefix인데 profile 관련한 prefix는 평범하게 /api/v1 이 맞지 않나 싶습니다.

그래서 저는 명세서랑 다른 브랜치에서 이미 수정해놨는데 이번 PR에서 미리 반영해두시죠!

2024-08-12 10:31 UTC, npureaun approved these changes

2024-08-13 02:17 UTC, mobzzzzz requested changes

2024-08-13 02:17 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
> +    fun changeProfileImageUrl(multipartFile: MultipartFile, mediaS3Service: MediaS3Service) {
Entity에 `MediaS3Service` 에 의존성이 생기면 좋지 않은 구조 같습니다!

`mediaS3Service.upload(multipartFile, S3FilePath.PROFILE.path)` 에서 나온 값을 사용하고 싶으신 거면 서비스에서 처리하고 나온 값으로 `changeProfileImageUrl` 하시는 게 좋을 것 같습니다.

2024-08-13 02:17 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    @PatchMapping(
`PATCH` 라고 하기엔 이 API로 한번에 바꿀 수 있는 내용이 많아서 `PUT`이 적합할 것 같습니다

2024-08-13 02:17 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +            member.profileImageUrl = profileUrl
이 부분도 changeProfileUrl 을 쓰면 될 것 같네요

2024-08-13 02:17 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        request.nickname?.let { member.changeNickname(request.nickname) }
다 잘 된 것 같고 추가로 `nickname` 중복 체크만 해주면 될 것 같습니다!

2024-08-13 10:01 UTC, mobzzzzz approved these changes
👍

2024-08-13 10:12 UTC, merged