:art: 로그인,회원가입 구현
spartaKotlinTeamSober/wachu_server pull request #27
Opened 2024-07-15 11:49 UTC by kotlin2024

## 요약

> 로그인, 회원가입 구현

## 작업 사항

> 기본적인 CRUD 구현

## 리뷰 요청 사항(선택)

> 

---

### 해결한 이슈

closes: #4

2024-07-15 12:44 UTC, mobzzzzz requested changes
구현하시느라 고생하셨습니다! Dto 변환 로직만 한번 점검 부탁드릴게요!

2024-07-15 12:44 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        ) throw RuntimeException("잘못된 비밀번호")
해당 부분도 check로 바꿔보는거 어떨까요?
RuntimeException은 보통 예상치 못한 런타임환경 에러로`INTERNAL_SERVER_ERROR` 로 처리하다보니  BAD_REQUEST로 떨궈야 할 것 같습니다!

2024-07-15 12:44 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        return SignUpResponse(id = member.id, email = email, nickname = nickname)
SignUppRequest, SignUpResponse 내부에 Dto <-> Entity 변환 로직 만들어주세요!

해당 방식은 일반적으로 필수는 아니지만 저희 시작할 때 정해놓은 컨벤션이니 한번 시도해보시는 것도 좋을 것 같아요!

물론 let, also 같은 scope function 까지는 쓰지 않으셔도 괜찮습니다!

2024-07-16 01:40 UTC, kotlin2024 commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        ) throw RuntimeException("잘못된 비밀번호")
해당 부분 check로 수정하였습니다

2024-07-16 01:42 UTC, kotlin2024 commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        return SignUpResponse(id = member.id, email = email, nickname = nickname)
signUpRequest 안에 변환 로직을 만들고 SignUpResponse의 변환로직은 Member 엔티티에 작성하였습니다. SignUpResponse의 변환 로직도 Member 엔티티가 아니라 SignUpResponse안에 작성하는것인지 아닌지 헷갈리는 부분이 조금 있습니다. (일단 챗지피티한테 물어봤을때는 Member 엔티티로 알려주길래 일단 그쪽으로 했습니다..)

2024-07-16 01:56 UTC, mobzzzzz requested changes
고생하셨습니다! 변환 로직 위치만 다시 한번 조정 부탁드릴게요!

2024-07-16 01:56 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
> +fun Member.toSignUpResponse(): SignUpResponse {
Entity는 시스템에서 어지간해선 최상위에 해당하는 고수준 모듈이라서 

'Member' 라는 Entity가 저수준 통신에서도 이용하는 DTO를 알게 되면 SignUpResponse 의 변경이 Member entity까지 전파가 됩니다! (ex: SignUpResponse에 profile_image_url을 추가하면 Member entity 내부에 있는 변환 로직도 수정해야함)

그래서 Entity는 Entity 스스로의 정보만 알고 있게 하는 것이 바람직하고 SignUpResponse 내부에 companion object로 `from(entity: Entity)` 를 작성하는 방식이 강의나 튜터링에서 가장 많이 나온 방식입니다!

```kotlin
companion object {
    fun fromEntity(entity: Entity): Dto {
        return Dto(/* ... */)
    }
}
```

2024-07-16 01:57 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        return SignUpResponse(id = member.id, email = email, nickname = nickname)
해당 부분 밑에 새로 리뷰 작성해봤습니다! 튜터링/강의에 기반한 내용인데 챗지의 생각에도 장단점이 존재할 수 있으니 보시고 resolve conversation 진행해주시면 됩니다!

2024-07-16 01:58 UTC, mobzzzzz commented
노티 테스트

2024-07-16 02:24 UTC, kotlin2024 commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
> +fun Member.toSignUpResponse(): SignUpResponse {
signUprequest와 signUpResponse 둘다 companion object 추가하였고 기존 member 엔티티에 있던 함수는 제거하였습니다

2024-07-16 02:27 UTC, mobzzzzz approved these changes
익숙하지 않은 방식이실텐데도 적극적으로 반영해주셔서 감사합니다! 
우선 Approve 하겠습니다 :+1:

TokenResponse의 토큰 생성 로직이 아직 서비스 로직에 남아있긴 하지만
토큰 생성 로직을 비즈니스 로직의 일부로 생각하는 경우도 있어서 
TokenResponse도 from으로 돌릴지의 여부는 형조님 의견에 맡기겠습니다!

그 외에도 SignUpRequest 내부에 유효성 검사는 나중에 이슈 분리를 진행해도 될 것 같고

SignUp에 대한 통합 테스트 코드등이 해당 PR에 존재할 수도 있겠지만
사실 로직만 봐도 유저 생성 자체는 연관 관계가 없고 워낙 가벼운 이슈라 필수로 다루지는 않으셔도 될 것 같습니다!

2024-07-16 02:55 UTC, merged