:sparkles: 페어링 도메인 crud 추가
spartaKotlinTeamSober/wachu_server pull request #34
Opened 2024-07-16 07:56 UTC by ckhcree

## 요약

> 페어링 crud

## 작업 사항

> 페어링 crud 추가 + 멤버리포지토리 펑션추가

## 리뷰 요청 사항(선택)

> 디티오(pairingrequest)에 엔티티로 변환하는 펑션 넣어서 서비스에서 사용했는데, 괜찮은가요?

---

### 해결한 이슈

closes: #8

2024-07-16 07:59 UTC, ckhcree commented
아직 테스트코드 찬준튜터님 수업 들어놓고 작성은 못햇습니다. 까먹고 바로 pr 날려버렷네여..ㅠㅠ
테스트코드 추가하고 머지로 넘어가겟습니다!

2024-07-16 08:05 UTC, mobzzzzz requested changes
고생하셨습니다! 금방 끝내셨네요 👍 

사소한 부분들 맞춰주시고, 여유가 되신다면 **테스트 코드** 작성도 한번 시도해보시면 좋겠습니다! 내부 로직도 별거 없고 CRUD가 딱히 없으니 생성이 잘 이루어지는지 보면 좋을 것 같네요
추가) 테스트 코드 부분 코멘트 지금 봤네요 ㅋㅋㅋ 화이팅!

2024-07-16 08:05 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        if (pairing.memberId != userPrincipal.memberId) {
이 부분 if문 그대로 쓰셔도 되고 MemberServiceImpl 에 보면 있는 `check` 같은거 써서 코드 depth 줄이는 것도 가능하고

throw는 `AccessDeniedException` 만들어놨으니 그걸 쓰시는걸 추천드리고

`pairing.memberId != userPrincipal.memberId` 이라는 권한 체크 로직은 다른 Pairing에서도 중복적으로 쓸 수 있으니 Pairing Entity 내부에 `hasPermission(memberId: Long, role: String)` 을 만들어서 Entity가 권한을 체크하게 구현해보시는 건 어떨까요?

2024-07-16 08:05 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +            ?: throw IllegalArgumentException("Member not found")
여태 강의/과제 하면서 익숙하신 `ModelNotFoundException` 쓰시는 걸 추천드립니다! 

`ModelNotFoundException` 로 Exception을 던지면 "404" 에러코드로 나가서 이해하기 더 좋아요

위에 있는 getPairing 에서도 바꿔주시면 좋을 것 같습니다!

2024-07-16 08:53 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        if (pairing.memberId != userPrincipal.memberId) {
체크 + AccessDeniedException 잘 사용된거 맞나요?
멤버 못찾을때도 모델낫파운드로 해놧습니당

2024-07-16 10:02 UTC, mobzzzzz requested changes
금방 다 처리해주셨네요! 한번만 수정해주시면 될 것 같습니다!

2024-07-16 10:02 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        check(pairing.memberId == userPrincipal.memberId) { AccessDeniedException("not your pairing") }
여기 이제 `pairing.hasPermission` 으로 바꿔주기만 하면 될 것 같아요!

2024-07-17 00:11 UTC, mobzzzzz requested changes

2024-07-17 00:11 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        pairing.hasPermission(userPrincipal.memberId, userPrincipal.role)
```
check(pairing.hasPermission(userPrincipal.memberId, userPrincipal.role)) { AccessDeniedException("not your pairing") }
```

이렇게 해주셔야 인가 처리가 됩니다! 수정하신 내용은 boolean 만 리턴받는 거라서 처리가 안되겠네요

2024-07-17 06:35 UTC, mobzzzzz approved these changes

2024-07-17 06:35 UTC, merged