:sparkles: 페어링 목록조회 queryDSL 페이지네이션
spartaKotlinTeamSober/wachu_server pull request #53
Opened 2024-07-19 04:37 UTC by ckhcree

## 요약

> 페어링 목록조회를 queryDSL 페이지네이션 함

## 작업 사항

> 해당펑션 서비스 및 컨트롤러 수정 + queryDSL용 리포지토리 생성 및 적용

## 리뷰 요청 사항(선택)

> 이게 된건지 잘 모루겟습니다ㅠㅠ. 
일단 h2 콘솔에서는 와인데이터 뜨는거 확인했는데요. 
스웨거에서 목록조회 하니까 아래화면 나와서 페이지네이션 여부 체크 필요합니다.
![image](https://github.com/user-attachments/assets/92052111-2a3c-4213-b4b9-d1987687d21f)

---

### 해결한 이슈

closes: #49

2024-07-19 05:24 UTC, mobzzzzz requested changes
403 Forbidden 나오는건 Access token 문제일 확률이 커보이네요
토큰을 다시 재발급 받아보시죠!

추가로 GET Method는 그냥 인증 없이 조회할 수 있게 수정도 고려해봐야 할것 같네요

2024-07-19 05:24 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        val pairingList = pairingRepository.findList(page, size)
findList 로 분리하기 보다는 기존에 정의해두신 findAll() 의 내용을 `return pairingQueryDslRepository.findList(page, size)` 로 바꾸시는 편이 좋을 것 같습니다!

그리고 page, size를 Repository에서 PageRequest로 만들어주는게 아니라 Controller 에서부터 PageRequest를 만들어서 매개변수로 넘겨주는 편이 실수 유발이 덜 될 것 같네요

2024-07-19 05:28 UTC, npureaun commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        val pairingList = pairingRepository.findList(page, size)
PageableDefault

2024-07-19 05:29 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        val pairingList = pairingRepository.findList(page, size)
지훈님 말씀대로 Controller에 `PageableDefault` 사용하면 Pageable 정보 쉽게 인자로 받을 수 있어요

2024-07-19 05:30 UTC, npureaun commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        val pairingList = pairingRepository.findList(page, size)
바로 지웠는데 바로 보셨군요..

2024-07-19 07:05 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        val pairingList = pairingRepository.findList(page, size)
맞게 수정이 되었는가요? 스웨거에서는 페어링이 없어서 빈 리스트 뜨는거보면 오키인거같아요.

2024-07-19 07:11 UTC, mobzzzzz requested changes

2024-07-19 07:11 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingQueryDslRepository.kt
> +        return page
`PageImpl` 객체로 만들어서 반환 타입이 `Page<Pairing>` 이 되게끔 만들어 주세요!

PageImpl 의 생성자는 이렇게 생겼는데 PageImpl() 생성자에 content, pageable, **total** 을 넣어주면 됩니다. 

그리고 여유가 되신다면 예를 들어 테스트 데이터 10개, page size를 2나 3처럼 적용해서 Pagination이 적용이 잘 되는지 확인하는 테스트 코드도 작성해보세요!

```kotlin
public PageImpl(List<T> content, Pageable pageable, long total) {

		super(content, pageable);

		this.total = pageable.toOptional().filter(it -> !content.isEmpty())//
				.filter(it -> it.getOffset() + it.getPageSize() > total)//
				.map(it -> it.getOffset() + content.size())//
				.orElse(total);
}
```

2024-07-20 06:28 UTC, npureaun approved these changes

2024-07-22 01:23 UTC, mobzzzzz requested changes

2024-07-22 01:23 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
> +        return pairingList.map { PairingResponse.from(it) }.toList()
toList를 하지 않고 Controller 자체도 `Page<PairingResponse>` 를 반환하게 설계해야 Pagination 이 100% 구현되었다고 할 수 있습니다!

Controller에 설계하신 반환값 자체도 `Page<PairingResponse>` 가 되게 설정해주세요!

2024-07-22 01:23 UTC, mobzzzzz commented on src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/controller/PairingControllerTest.kt
> +    fun `페이지넘버와 사이즈에 해당하는 pairing 목록을 반환한다`() {
요 테스트는 저희가 작성한 Service, Repository의 로직보다는 `PageRequest`, `PageImpl`처럼 이미 문제없는 객체에 대한 테스트 코드라서 굳이 없어도 될 것 같습니다!

2024-07-22 03:20 UTC, mobzzzzz approved these changes
빌드랑 API 호출했을때 에러 안나면 머지해주시면 될 것 같습니다!
고생하셨습니다 👍

2024-07-22 04:08 UTC, merged