:sparkles: 페어링 FetchJoin
spartaKotlinTeamSober/wachu_server pull request #63
Opened 2024-07-23 09:00 UTC by ckhcree

## 요약

> 페어링과 와인을 FetchJoin 
Projection, Pagination 중 Pagination 택,
Pagination + Fetch join 2단계 분리

## 작업 사항

>  - [x] JPA 연관관계 설정 (단방향 @ManyToOne 권장)
>  - [x]  QueryDSL Fetch join 설정
>  - [ ]  QueryDSL 적용 전후의 쿼리 / 성능 시간 비교
>  - [x]  테스트 코드 작성

## 리뷰 요청 사항(선택)

> 페치조인이 첨이라 좀 어색하네여
리뷰 주시면 반영해서 수정하고  before/after 성능비교 드가겟슴다

---

### 해결한 이슈

closes: # 아직 안닫음

2024-07-23 10:30 UTC, mobzzzzz requested changes
연관 관계가 생겨서 생성, 테스트코드같은거 바꿀때 골치아프셨을텐데 많이 바꿔주셨네요!

한번 변경내역 체크해주시고 성능 비교는 아직 데이터가 적어서 크게 차이가 안나긴 하던데 만약 페어링 테스트 데이터를 100~1000개씩 테스트해볼 수 있으면 유의미한 차이가 나는지 확인해볼수도 있을 것 같습니다.

2024-07-23 10:30 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingResponse.kt
> +                wineId = pairing.wine.id,
이제 Pairing Entity가 Wine 을 연관관계로 가지고 있고 Fetch join도 하고 있으니 Response의 `wineId` 를 `wine: WineResponse` 로 바꾸고 `WineResponse.from(pairing.wine)` 같은 방식으로 Wine 의 정보를 Pairing과 함께 반환해주시면 좋을 것 같습니다!

2024-07-23 10:30 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingQueryDslRepository.kt
> +                .where(pairing.id.eq(basicPairing.id))
2단계 쿼리를 활용해주셨네요! 그런데 `Where` 문을 단일로 비교하면 `in` query 보다 조금 더 느릴 수도 있습니다.

2단계 쿼리를 한다면 `in` 을 쓰거나 아니면 아예 WinePromotion 에 있는 Fetch join처럼 쿼리 하나로 해결해도 되지 않을까 싶네요!

이 부분은 저도 잘못알고 있던 부분인데 `@ManyToOne` 관계에선 Fetch join + Pagination 을 해도 연관 관계의 대상이 또 연관 관계를 가지거나 하는게 아니면 OOM 경고가 나오지 않더라구요!

2024-07-23 12:28 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingResponse.kt
> +                wineId = pairing.wine.id,
맞춰서 테스트코드도 수정하였습니다!

2024-07-23 12:30 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingQueryDslRepository.kt
> +                .where(pairing.id.eq(basicPairing.id))
아예 하나로 합쳤습니다. 코드가 줄어드니까 좋으네요

2024-07-24 01:11 UTC, mobzzzzz approved these changes
고생하셨습니다! 👍

2024-07-24 01:43 UTC, merged