Feat/14 s3 image upload
spartaKotlinTeamSober/wachu_server pull request #64
Opened 2024-07-23 10:22 UTC by npureaun

- PR 제목은 다음 양식을 사용해주세요 : [Gitmoji] 제목
- 기능추가 :sparkles:
- 버그픽스 :bug:
- 문서작업 :memo:
- 테스트코드 :white_check_mark:
- 그외에도 gitmoji로  
--여기까지 삭제 후 PR 내용 작성
## 요약

> 간단 요약

## 작업 사항

1. S3 라이브러리 추가
2. 각각의 도메인에 맞게 비즈니스 로직 추가
3. 그에 맞게 테스트 코드 수정/작성
4. reivew 멀티타입미디어 테스트 코드가 조금 이상함.
5.  멀티타입미디어에 미디어 타입모킹을 해도 자꾸 예외처리 과정에서 걸러짐.
6. 그렇다고 타입모킹을 빼면 그건 그거대로 모킹오류가 나는 상황
7. 그러나 실제 로직은 잘 돌아감  

## 리뷰 요청 사항(선택)

> 리뷰시 봐주었으면 하는 부분이 있다면 적어주세요
리뷰 도메인을 핵심으로 봐주세요.
-참고사항- 
1차 적으로 직렬로직으로 되어 있지만, 이미지용량과 파일이 많아지면 그만큼 프로그램이 느려집니다.
 이를 병렬처리등으로 성능개선이 필요해 보입니다. 
---

### 해결한 이슈

closes: #14 
closes: #41

2024-07-23 10:40 UTC, mobzzzzz requested changes
예상보다 엄청나게 규모가 크네요! 특히 Review Multimedia는 테이블만 분리하면 끝일줄 알았는데 생각 이상으로 많이 복잡한 API가 나와서 놀랬습니다.

그리고 업로드 테스트는 AWS까지 들여다보면서 작업하시느라 귀찮았을텐데 고생하셨습니다!

다만 전체적으로 Code style 적용이 되다 말다 하는 것 같은데 한번 체크 부탁드릴게요!

sparta.nbcamp.wachu 폴더에 우클릭하고 코드 서식 다시 지정하면 하위 디렉터리도 전부 지정 가능한 옵션이 있는데 아마 이걸로 하면 빌드가 꼬이거나 하는 일은 없을겁니다.

2024-07-23 10:40 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingRequest.kt
> +        fun toEntity(memberId: Long, pairingRequest: PairingRequest,imageUrl:String?): Pairing {
전체적으로 Code style(Lint) 처리 한번만 부탁드려요!

2024-07-23 11:00 UTC, npureaun commented
1. pageble과 컨플릭트 해결해도 코드단에서 문제가 있었네요. 이거 해결했습니다.
2. 코드 스타일 적용 하였습니다.!

2024-07-24 01:45 UTC, mobzzzzz approved these changes

2024-07-24 02:25 UTC, npureaun commented
컨플릭트 두번 선넘네

2024-07-24 02:29 UTC, mobzzzzz commented
ㅋㅋㅋㅋ 코드 스타일 일괄적용때문인 것 같은데 한번씩 해줘야겠네요
Action on save만으로는 저장 자주 누르는거 아니면 빠지는 부분이 많은 것 같습니다

2024-07-24 02:37 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/controller/v1/PairingController.kt
> +        @RequestPart pairingRequest: PairingRequest,
이미지를 멀티파트로 받을려면 기존 리퀘스트에도 RequestPart를 쓰는거군요

2024-07-24 02:40 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/ReviewMediaType.kt
> +    VIDEO
비디오도 넣을수잇서요?? 홀리몰리~~

2024-07-24 02:49 UTC, ckhcree approved these changes
먼가 굉장한 업그레이드가 되었군요. 수고하셨습니다!!

2024-07-24 02:54 UTC, npureaun commented on src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/ReviewMediaType.kt
> +    VIDEO
나중에 추가구현 확장성때문에 만들어 둔거라 아직 검증된건 없습니다! 용량문제로 동영상은 URL만 저장하고 이미지는 S3로 올리는 형식이어떨까 싶습니다

2024-07-24 05:21 UTC, merged