:sparkles: Feat/55  OAuth2
spartaKotlinTeamSober/wachu_server pull request #76
Opened 2024-07-27 01:32 UTC by kotlin2024

## 요약

> 네이버,카카오 소셜 로그인 기능 구현

## 작업 사항

> 

로그인시 pageUrl이 나오며 해당 URL로 접속시 DTO형태로 반환

네이버
![네이버](https://github.com/user-attachments/assets/9456257a-8527-4613-8333-b12ef69012ae)

![네이버 콜백](https://github.com/user-attachments/assets/01d43208-c151-4fe6-a36a-98a4fc567c1f)

카카오

![카카오](https://github.com/user-attachments/assets/8d9fd236-8f6d-43b4-8e30-c615f982a548)

![카카오 콜백](https://github.com/user-attachments/assets/10541cd7-84ea-4865-a2fc-9e14c6c48769)

소셜 로그인,회원가입 로직 구현

소셜 로그인시 ncikname이 기존 서비스의 nickname과 중복될수도 있으므로 소셜 로그인 회원가입시 nickname을 request에 넣었습니다.

기존 멤버 provider,providerId추가

![member엔티티](https://github.com/user-attachments/assets/db420d4c-a047-4fb7-8bae-437a623f776f)

providerId의 경우 네이버나 카카오에서 넘겨받은 값을 dto로 전환할때 String값으로 넘겨받아서 그냥 String타입으로 설정하였습니다.

## 리뷰 요청 사항(선택)

> 
![고려사항](https://github.com/user-attachments/assets/f50255c6-1654-428f-854a-ac877b6afeac)

소셜 로그인과 회원가입 기능을 임시로 만들었는데, 프론트로 넘겨주는건지 어떻게 하는지 잘 모르겠어서 일단 컨트롤러에 연결은 하지 않고 임시로 작성만 해보았습니다.
그리고 password에 providerId와 providerName을 합친 문자열로 임시로 넣었는데, 다른 고유값을 받아서 비밀번호로 설정할 수도 있을것같습니다. 

---

### 해결한 이슈

closes: #55

2024-07-27 10:19 UTC, npureaun reviewed
엄청난 작업량이네요...고생이 많으셨을거 같습니다..!

2024-07-27 10:19 UTC, npureaun commented on src/test/kotlin/sparta/nbcamp/wachu/domain/security/ImsiTest.kt
> +    fun imsi() {
이 테스트는 무엇인가요?

2024-07-28 12:40 UTC, mobzzzzz requested changes
고생하셨습니다!

정책쪽은 말로만 했던 설명을 다시 리뷰로 적어보긴 했는데 글로 보면 복잡하지만 코드로 바꾸면 간단한 변경사항입니다!

2024-07-28 12:40 UTC, mobzzzzz commented on build.gradle.kts
> +    implementation ("org.springframework.boot:spring-boot-starter-oauth2-client")
구현하신 기능에 Spring boot oauth2 안쓰시지 않았나요? 만약 안쓰셨으면 클라이언트 / 리소스 제거 부탁드릴게요!

2024-07-28 12:40 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SocialSignUpRequest.kt
> +data class SocialSignUpRequest(
아직 구현이 안됐으니 불확실하긴 하지만 의도한 순서는 이렇습니다

1. FE에서 API 호출은 `OAuthResponse` 의 정보를 받아 필요한 정보는 미리 Field에 채워둠
2. 채워둔 필드 + 부족한 필드를 포함해 평범한 Signup을 진행하는데 `provider`, `providerId` 를 추가로 body에 담아 보내서 social login으로 진행한 회원가입임을 구분함 

미리 생각해본건 회원가입 화면 자체가 소셜 유저가 진입하는 회원가입 화면이 따로 있고 닉네임 / 프로필이미지는 소셜 정보로 미리 채워져있는 상태에서 이메일만 추가로 인증받아 추가되는 형태입니다. 

패스워드는 적어주신 것처럼 `${oAuthRequest.provider}+${oAuthRequest.providerId}` 같은 형태거나 고유한 해쉬값이거나 어쨌든 암호화하는 방식이 될 텐데 이걸 FE에서 처리하면 비밀번호 암호화 방식이 노출되니까 암호화는 BE에서 진행하는게 맞을 것 같습니다.

그래서 `SocialSignUpRequest` 와 Social용 회원가입 API를 분리하는게 아니라 `SignUpRequest` 에 `Provider`, `ProviderId` 를 기본값 null로 설정해서 받게할지 고민중입니다.

SignUpController 에서 `provider` 가 null인지 아닌지로 구분해서 다른 service 로직을 호출하게 하는 방식도 괜찮을 것 같네요

2024-07-28 12:40 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
> +    @Column(name = "providerId")
provider_id 로 수정 부탁드려요!

2024-07-28 12:40 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        val member = SignUpRequest.toEntity(
위에서 회원가입 방식에 다룬 내용의 연장선인데 toEntity 내용 자체를 변경하게 되지 않을까 싶습니다.

추가로 `SignUpRequest` 가 `SignUpRequest`를 생성해 호출하는 방식이 되어 기괴한데 `Companion obejct function`이 아니라 `member function` 으로 변경도 필요할 것 같네요!

2024-07-30 02:58 UTC, kotlin2024 commented
일반 로그인
![일반로그인](https://github.com/user-attachments/assets/b4d697fe-eae7-4552-b97e-0d50190cf869)


일반 로그인시 h2저장
![일반로그인 h2](https://github.com/user-attachments/assets/710c5220-a050-45b2-8e3f-ddab45f6b803)

소셜 로그인
![소셜로그인](https://github.com/user-attachments/assets/82bacd79-a572-45c1-ac11-a078b852bf20)

소셜 로그인시 h2 저장
![소셜 로그인 H2](https://github.com/user-attachments/assets/3aa1ac9b-91f1-4194-9650-8d9008ded84d)

null여부에 따라 다른  service 로직 수행
![NULL여부에 따른 로그인 분리](https://github.com/user-attachments/assets/cb6809b7-6c1c-4612-b9be-b5c0df21de77)

2024-07-30 12:20 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +        check(codeService.checkCode(request.email, request.code)) { "인증코드가 맞지 않음" }
결론:

- Scope의 대량 축소
    1. 추가 회원가입 페이지를 아예 사용하지 않게 변경
    2. OAuth 회원가입시 정보가 비어있더라도 즉시 회원가입 진행후 Access token을 발급함
    3. 회원가입 진행을 위해 ERD의 축소
        1. email, nickname 을 nullable하게 변경함

2024-07-31 07:52 UTC, mobzzzzz requested changes

2024-07-31 07:52 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
> +            val accessToken = jwtTokenManager.generateToken(memberId = memberId, memberRole = MemberRole.MEMBER)
memberRepository.addMember 를 진행하고 난 뒤 Return 된 Member는 Id값이 있을 테니까 `findByProviderAndProviderId` 를 한 번 더 진행하지 않고 .let scope로 한번에 처리할 수 있어 보입니다!

2024-07-31 07:52 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/controller/OAuth2LoginController.kt
> +@CrossOrigin(origins = ["http://localhost:8080"])
CORS 관련 설정은 Security에서 빼놔서 없어도 될텐데 빼고 테스트 해보셔도 될 것 같습니다

2024-07-31 07:52 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/TokenResponse.kt
> +data class TokenResponse(
Member domain의 TokenResponse가 있으니깐 이건 제거하셔도 될 것 같습니다!

2024-07-31 07:52 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SocialSignUpRequest.kt
> +// data class SocialSignUpRequest(
안쓰게 될 파일은 제거하셔도 좋습니다!

2024-07-31 07:52 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/CompleteSocialSignUp.kt
> +// data class CompleteSignUp(
안쓰게 될 파일은 제거하셔도 좋습니다!

2024-07-31 11:24 UTC, mobzzzzz approved these changes
고생하셨습니다! 👍 
머지되고 나면 FE 로그인에도 버튼좀 추가해봐야겠네요!

2024-08-01 08:04 UTC, ckhcree approved these changes
넘므 수고많으셧습니다!!

2024-08-01 09:32 UTC, merged