:sparkles: 이메일 비동기 스레드
spartaKotlinTeamSober/wachu_server pull request #96
Opened 2024-08-07 02:11 UTC by ckhcree

## 요약

> 이메일발송 속도 아니고 사용성 개선

## 작업 사항

> gmail smtp 서버 관련 속도 개선은 제한적이라 -> 비동기 스레드로 다른 api 안막히게 수정

## 리뷰 요청 사항(선택)

> ![image](https://github.com/user-attachments/assets/17cce612-0f62-4378-9b9e-a8a87fe937ec)
기본 스레드수 2
최대 스레드수 5
작업 대기열 크기 10
괜찮을가요?

---

### 해결한 이슈

closes: #93

2024-08-07 06:25 UTC, mobzzzzz requested changes

2024-08-07 06:25 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    fun sendValidationCode(@RequestBody request: SendCodeRequest): CompletableFuture<String> {
Async를 써주셨네요! 저도 처음 봐서 레퍼런스 검색해보니 자주 쓰는 비동기 태스크같아서 배워갑니다.

그런데 반환형이 `ResponseEntity` 가 아니라 `CompletableFuture`인 이유는 따로 있나요? 

없다면 프론트가 `CompletableFuture` 를 받아도 딱히 의미 없을 거라서 `ResponseEntity` 로 다시 수정되면 좋을 것 같습니다.

추가로 CompletableFuture 를 사용하는 Async는 Java 8 버전이라고 확인했는데 저희가 사용하는 Java 17 또는 Kotlin에서 비동기 대안으로 사용할만한 것도 있는지 알아두면 구현 기능 설명하실 때 더 좋을 것 같습니다! 
(이건 저도 모르는데 Java 8 시절 기능보다 좋은 비동기 처리가 있긴 있겠지 하고 남겨봅니다)

2024-08-07 06:43 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    fun sendValidationCode(@RequestBody request: SendCodeRequest): CompletableFuture<String> {
스웨거에서 리스폰스바디가 
{
  "done": false,
  "cancelled": false,
  "completedExceptionally": false,
  "numberOfDependents": 0
}
이런식으로 반환됐어서 바꿧었는데요
프론트에서 처리하는데 문제없다면 ResponseEntity로 다시 바꾸겟습니다!

추가적으로 업뎃된 비동기 있는지는 또 서치해보겠습니다!

2024-08-07 06:47 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    fun sendValidationCode(@RequestBody request: SendCodeRequest): CompletableFuture<String> {
이메일이 발송되었는지 결정하는게 Google 메일 서버쪽이라 Completable 정보가 있어도 

사실 대부분 비동기 상황이 끝나지 않은 상태인 `done: false`인 채로 반환될 거라서 (구글 이메일 서버로 송신 요청 보냈으니 서버는 할일 끝나서)

 `ResponseEntity<String>` 으로 해서 `return ResponseEntity.ok("Email send successfully")` 같은 식으로 처리하면 되는 식일 것 같습니다! 그래서 `CodeService` 에서도 `CompletableFuture`를 굳이 return 해주지 않아도 되지 않나 싶네요

2024-08-07 07:20 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    fun sendValidationCode(@RequestBody request: SendCodeRequest): CompletableFuture<String> {
![image](https://github.com/user-attachments/assets/0f725ea3-0438-4c63-aeae-1541577787ad)
다시 보니까 @Async 어노테이션 붙여서 비동기로 하려면 반환타입이 Future, CompletableFuture, 또는 void 여야 한다고 합니다

2024-08-07 07:30 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +    fun sendValidationCode(@RequestBody request: SendCodeRequest): CompletableFuture<String> {
그러면 서비스 코드는 그대로 `CompletableFuture` 반환하게 하고 Controller만 그대로 두죠

Controller 코드 부분을
```kotlin
codeService.sendCode(/**/)
return ResponseEntity.ok("Email send successfully")
```

이렇게 수정해서 사용하면 될 것 같아요

2024-08-07 07:46 UTC, mobzzzzz commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +        return codeService.sendCode(request.email)
```kotlin
fun sendValidationCode(@RequestBody request: SendCodeRequest): ResponseEntity<String> {
codeService.sendCode(request.email) // return된 값 안씀
return ResponseEntity.ok("Email send successfully")
```

이런 얘기였습니다!

2024-08-07 07:56 UTC, ckhcree commented on src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
> +        return codeService.sendCode(request.email)
늦게 봐가지구 이거까지 다 반영해서 최대한 간결하게 바꿔봣습니다!

2024-08-07 07:57 UTC, mobzzzzz approved these changes
고생하셨습니다! 실제로 테스트할 때는 API는 바로 성공하고 메일은 몇초뒤에 발신되는 식으로 테스트 되는지만 확인하시면 될 것 같습니다!

2024-08-08 10:40 UTC, kotlin2024 approved these changes

2024-08-08 10:50 UTC, merged